### ISSUE TITLE
GetSwingMagnitude always returning Large

### ISSUE THREAD

**Issue by carloslancha** [JakeS0ft/USaber#1]
Hi!

I'm running the example MPU6050MotionManager and when I swing or clash I'm always getting Large. I played with different thresholds but I didn't make it work.

Could you pleas help me to find out what I'm missing?

Thanks!

- Arduino Nano
- MPU6050 (GY-521) Calibrated with its offsets
- VCC to 3v3
- SCL to A5
- SDA to A4
- INT to D2
- GND to GND

**Comment by JakeS0ft** [comment]
It looks like when Neskweek created the MPU6050MotionManager, he didn't add an override for the GetSwingMagnitude() method. The default implementation of this method in the base AMotionManager class will always return Large, so that explains it.
For now, the answer is that swing magnitude discrimination isn't supported by the class. You can still use it, but it'll always report a Large swing. I'll put it on my to-do list to add swing magnitude discrimination.

**Comment by JakeS0ft** [comment]
Fix approved merged with master. Thank you, @carloslancha!
